import { Action, DB, Item, Log } from "./types";
import { addDays, daysBetween, today } from "./dates";

/**
 * Progress flows upward: an item's progress is its own tracker progress,
 * or — when it has none — the average progress of its children, recursively.
 */

export function children(db: DB, itemId: string): Item[] {
  return db.items
    .filter((i) => i.parentId === itemId && i.status !== "archived")
    .sort((a, b) => a.position - b.position);
}

export function ownProgress(item: Item): number | null {
  if (item.status === "done") return 1;
  switch (item.tracker) {
    case "check":
      return item.completedAt ? 1 : 0;
    case "percent":
      return clamp01(item.current / 100);
    case "counter":
    case "money":
    case "book":
      return item.target && item.target > 0 ? clamp01(item.current / item.target) : null;
    case "habit":
    case "none":
      return null;
  }
}

export function itemProgress(db: DB, item: Item, depth = 0): number | null {
  const own = ownProgress(item);
  if (own !== null) return own;
  if (depth > 12) return null; // guard against pathological cycles
  const kids = children(db, item.id);
  const kidVals = kids
    .map((k) => itemProgress(db, k, depth + 1))
    .filter((v): v is number => v !== null);
  if (kidVals.length === 0) return item.status === "done" ? 1 : null;
  return kidVals.reduce((a, b) => a + b, 0) / kidVals.length;
}

export function ancestors(db: DB, item: Item): Item[] {
  const out: Item[] = [];
  let cur = item;
  const seen = new Set<string>([item.id]);
  while (cur.parentId) {
    const p = db.items.find((i) => i.id === cur.parentId);
    if (!p || seen.has(p.id)) break;
    out.push(p);
    seen.add(p.id);
    cur = p;
  }
  return out;
}

export function descendants(db: DB, itemId: string): Item[] {
  const out: Item[] = [];
  const queue = [itemId];
  const seen = new Set<string>();
  while (queue.length) {
    const id = queue.shift()!;
    for (const kid of db.items.filter((i) => i.parentId === id)) {
      if (seen.has(kid.id)) continue;
      seen.add(kid.id);
      out.push(kid);
      queue.push(kid.id);
    }
  }
  return out;
}

/* ————— Habits & streaks ————— */

export function habitDays(logs: Log[], itemId: string): Set<string> {
  return new Set(logs.filter((l) => l.itemId === itemId && l.value > 0).map((l) => l.date));
}

export function currentStreak(days: Set<string>, anchor = today()): number {
  let streak = 0;
  let d = anchor;
  // today not logged yet doesn't break the streak
  if (!days.has(d)) d = addDays(d, -1);
  while (days.has(d)) {
    streak++;
    d = addDays(d, -1);
  }
  return streak;
}

export function bestStreak(days: Set<string>): number {
  const sorted = [...days].sort();
  let best = 0;
  let run = 0;
  let prev: string | null = null;
  for (const d of sorted) {
    run = prev && daysBetween(prev, d) === 1 ? run + 1 : 1;
    best = Math.max(best, run);
    prev = d;
  }
  return best;
}

/* ————— Today ————— */

export interface TodayEntry {
  /** real action row, or a virtual one generated by a habit's cadence */
  action: Action;
  item: Item | null;
  virtualHabit: boolean;
  /** action carried forward from an earlier day */
  carriedFrom: string | null;
}

function habitDueToday(item: Item, day: string): boolean {
  if (item.kind !== "habit" || item.status !== "active") return false;
  const cadence = item.cadence ?? "daily";
  const dow = new Date(day + "T12:00:00").getDay();
  if (cadence === "weekdays") return dow >= 1 && dow <= 5;
  return true; // daily & weekly both surface daily; weekly is satisfied by any day
}

export function todayEntries(db: DB, day = today()): TodayEntry[] {
  const entries: TodayEntry[] = [];

  // 1. real actions for today
  for (const a of db.actions.filter((a) => a.date === day)) {
    entries.push({
      action: a,
      item: a.itemId ? db.items.find((i) => i.id === a.itemId) ?? null : null,
      virtualHabit: false,
      carriedFrom: null,
    });
  }

  // 2. unfinished actions from earlier days — carried forward, never shamed
  for (const a of db.actions.filter((a) => !a.done && a.date < day)) {
    entries.push({
      action: a,
      item: a.itemId ? db.items.find((i) => i.id === a.itemId) ?? null : null,
      virtualHabit: false,
      carriedFrom: a.date,
    });
  }

  // 3. habits due today (virtual — completing writes a log)
  const logged = new Set(db.logs.filter((l) => l.date === day).map((l) => l.itemId));
  for (const h of db.items.filter((i) => habitDueToday(i, day))) {
    const hasRealAction = entries.some((e) => e.action.itemId === h.id);
    if (hasRealAction) continue;
    entries.push({
      action: {
        id: `habit:${h.id}:${day}`,
        itemId: h.id,
        title: h.title,
        date: day,
        done: logged.has(h.id),
        doneAt: null,
        amount: 1,
        createdAt: h.createdAt,
      },
      item: h,
      virtualHabit: true,
      carriedFrom: null,
    });
  }

  return entries.sort((a, b) => {
    if (a.action.done !== b.action.done) return a.action.done ? 1 : -1;
    return a.action.createdAt - b.action.createdAt;
  });
}

/* ————— Aggregates for reviews & dashboards ————— */

export function completionsInRange(db: DB, start: string, end: string) {
  const doneActions = db.actions.filter((a) => a.done && a.date >= start && a.date <= end);
  const habitLogs = db.logs.filter((l) => l.date >= start && l.date <= end && l.value > 0);
  const planned = db.actions.filter((a) => a.date >= start && a.date <= end);
  return { doneActions, habitLogs, planned };
}

export function areaOfItem(db: DB, item: Item | null): string | null {
  let cur = item;
  const seen = new Set<string>();
  while (cur) {
    if (cur.areaId) return cur.areaId;
    if (!cur.parentId || seen.has(cur.parentId)) return null;
    seen.add(cur.parentId);
    cur = db.items.find((i) => i.id === cur!.parentId) ?? null;
  }
  return null;
}

function clamp01(v: number): number {
  return Math.max(0, Math.min(1, v));
}

export function formatValue(item: Item, v: number): string {
  const unit = item.unit ?? "";
  if (item.tracker === "money") {
    return `${unit || "₹"}${v.toLocaleString()}`;
  }
  if (item.tracker === "percent") return `${Math.round(v)}%`;
  return unit ? `${v.toLocaleString()} ${unit}` : v.toLocaleString();
}
